[package]
name = "guest_code_for_zk_proof"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "^3.0.3", default-features = false, features = ['std'] }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1", default-features = false, features = ["alloc"] }