[package]
name = "parse_onnx"
version = "0.1.0"
edition = "2024"

[dependencies]
tract-onnx = "0.18.0"
tract-core = "0.18.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
time = "0.3.44"
