[package]
name = "methods"
version = "0.1.0"
edition = "2021"

[build-dependencies]
risc0-build = { version = "^3.0.3" }

[package.metadata.risc0]
methods = ["guest"]

[dependencies]
serde = "1.0"
serde_json = "1.0"