[package]
name = "LinearRegression"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
ort = "=2.0.0-rc.10"
ndarray = "0.15"
anyhow = "1.0.100"
openssl-sys = { version = "0.9", features = ["vendored"] }
risc0-zkvm = { version = "3.0", default-features = false, features = ["std"] }